const spots={
brighton:{name:'Brighton West Pier',type:'coast',lat:50.8195,lon:-.1517,sea:180,tide:'medium',access:'Public beach launch; check Brighton & Hove seafront notices',alt:'Ardingly Reservoir',meta:'19 miles · managed inland water'},
poole:{name:'Poole Harbour — Hamworthy',type:'harbour',lat:50.7116,lon:-1.9936,sea:115,tide:'high',access:'Established harbour launch; local harbour rules apply',alt:'Longham Lakes',meta:'8 miles · operator permission required'},
hayling:{name:'Hayling Island — West Beach',type:'coast',lat:50.7799,lon:-.9705,sea:180,tide:'high',access:'Established watersports beach; observe zoned areas',alt:'Emsworth Channel',meta:'7 miles · tidal, club-led access'},
camber:{name:'Camber Sands',type:'coast',lat:50.9309,lon:.7983,sea:155,tide:'high',access:'Public beach; seasonal zones and RNLI advice apply',alt:'Bewl Water',meta:'28 miles · paid launch / operator rules',rnli:{status:'Seasonal RNLI patrol',dates:'Central: weekends 3 Apr–17 May; daily 23 May–27 Sep · 10am–6pm',start:'2026-05-23',end:'2026-09-27',hours:[10,18],url:'https://rnli.org/find-my-nearest/lifeguarded-beaches/camber-central-beach',checked:'2026-09-19'}},
newquay:{name:'Fistral Beach, Newquay',type:'coast',lat:50.4165,lon:-5.1007,sea:290,tide:'medium',access:'Public beach; surf priority and local zoning apply',alt:'Stithians Lake',meta:'22 miles · activity-centre access',rnli:{status:'Long-season RNLI patrol',dates:'Daily 3 Apr–1 Nov 2026 · 10am–6pm',start:'2026-04-03',end:'2026-11-01',hours:[10,18],url:'https://rnli.org/find-my-nearest/lifeguarded-beaches/newquay-fistral-beach',checked:'2026-09-19'}},
tynemouth:{name:'Tynemouth Longsands',type:'coast',lat:55.0271,lon:-1.4246,sea:75,tide:'medium',access:'Public beach; use designated activity areas',alt:'Killingworth Lake',meta:'8 miles · club/operator access',rnli:{status:'RNLI seasonal patrol verified',dates:'Daily 23 May–6 Sep 2026 · 10am–6pm · no flags means no lifeguard',start:'2026-05-23',end:'2026-09-06',hours:[10,18],url:'https://rnli.org/find-my-nearest/lifeguarded-beaches/tynemouth-longsands-beach',checked:'2026-09-19'}},
abersoch:{name:'Abersoch Main Beach',type:'coast',lat:52.8246,lon:-4.5073,sea:115,tide:'high',access:'Recognised launch; harbour and seasonal rules apply',alt:'Llyn Padarn',meta:'35 miles · recognised activity venue'},
ardingly:{name:'Ardingly Reservoir',type:'reservoir',lat:51.055,lon:-.1,sea:null,tide:'none',access:'Managed watersports venue — pre-booking may be required',alt:'Brighton West Pier',meta:'19 miles · coastal alternative'},
bewl:{name:'Bewl Water',type:'reservoir',lat:51.0748,lon:.3959,sea:null,tide:'none',access:'Managed reservoir — launch only under operator rules',alt:'Camber Sands',meta:'28 miles · coastal alternative'},
stithians:{name:'Stithians Lake',type:'reservoir',lat:50.1838,lon:-5.2248,sea:null,tide:'none',access:'Managed activity centre — session rules and fees apply',alt:'Fistral Beach, Newquay',meta:'22 miles · coastal alternative'},
llanberis:{name:'Llyn Padarn — Llanberis',type:'lake',lat:53.1204,lon:-4.1317,sea:null,tide:'none',access:'Recognised paddling area; check local parking and launch notices',alt:'Abersoch Main Beach',meta:'35 miles · coastal alternative'},
wye:{name:'River Wye — Symonds Yat',type:'river',lat:51.8375,lon:-2.64,sea:null,tide:'none',access:'Recognised paddling reach; access agreements and levels apply',alt:'Llandegfedd Lake',meta:'25 miles · managed reservoir'},...window.EXTRA_SPOTS
};
const sports={sup:'SUP',wing:'Wing foil',windsurf:'Windsurf',kite:'Kitesurf'}, state={mode:'paddle',sport:'sup',freeSport:'sup',skill:'beginner',skills:{sup:'beginner',wing:'beginner',windsurf:'beginner',kite:'beginner'},spot:null,checks:[0,0,0,0],live:null,currentLive:null,marine:null,sun:[],hourly:[],allHours:[],outlook:[],selectedTime:null};
Object.values(spots).forEach(s=>{if(s.sports?.includes('wing')&&!s.sports.includes('windsurf')&&s.windVenue!==false)s.sports.push('windsurf')});
Object.assign(spots.strangford,{hazard:{severity:'extreme',title:'Strangford Narrows tidal stream',copy:'The Narrows carry strong tidal streams over boulder-strewn ground. This launch is inside the lough; do not turn it into an unguided Narrows trip.',source:'https://sac.jncc.gov.uk/site/UK0016618'}});
Object.assign(spots.calshot,{hazard:{severity:'high',title:'Solent shipping and tidal channels',copy:'Stay inside the designated Calshot watersports area, obey the seasonal kite restriction and keep clear of the deep-water shipping channel and moving prohibited zones.',source:'https://www.southamptonvts.co.uk/media/u1tfg3nu/sou-lntm-2026-018-port-of-southampton-designated-watersports-areas.pdf'}});
Object.assign(spots.portland,{hazard:{severity:'context',title:'Portland Race outside the harbour',copy:'Portland Harbour can be comparatively sheltered; Portland Race is not. Do not infer that a green harbour verdict makes the waters off Portland Bill safe.',source:'https://assets.publishing.service.gov.uk/media/5a7af54240f0b66a2fc040a8/SEA8_TechRep_Rec_Boating.pdf'}});
Object.assign(spots.daymer_bay,{hazard:{severity:'high',title:'Camel estuary current and traffic',copy:'Tide, shifting banks and boat traffic can turn a sheltered-looking bay into a poor choice. Stay out of the navigation channel and verify local tide advice.',source:'https://www.gov.uk/government/publications/mgn-715-mf-recommended-best-practice-for-respectful-and-safe-operation/mgn-715-mf-recommended-best-practice-for-respectful-and-safe-operation-in-shared-spaces'}});
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)], compass=d=>['N','NE','E','SE','S','SW','W','NW'][Math.round(((d||0)%360+360)%360/45)%8], diff=(a,b)=>Math.abs(((a-b+540)%360)-180);
const relation=(from,sea)=>{if(sea==null)return'Not applicable';const a=diff(from,sea);return a<=45?'Onshore':a<90?'Cross-onshore':a<135?'Cross-offshore':'Offshore'};
function rnliPatrolState(s,at=new Date()){let r=s.rnli;if(!r?.start||!r?.end)return{active:false,label:r?'Check current flags':'No verified patrol data'};let day=at.toISOString().slice(0,10),hour=at.getHours(),active=day>=r.start&&day<=r.end&&hour>=(r.hours?.[0]??0)&&hour<(r.hours?.[1]??24);return{active,label:active?'RNLI patrol scheduled now — confirm flags':day<r.start?'RNLI season has not started':'Outside verified RNLI patrol dates'}}
const time=x=>new Date(x).toLocaleTimeString('en-GB',{hour:'numeric',minute:'2-digit',hour12:true}).replace(' ','');
let map,markers={},windMarker,waveMarker,mapLayers={};
function signalFor(s,d){if(s.sports&&!s.sports.includes(state.sport))return'grey';if(s.type==='river'&&s.gaugeValidated!==true)return'grey';let n=windFit(d.wind).n,a=relation(d.dir,s.sea);if(a==='Offshore')n+=state.sport==='sup'||state.sport==='kite'?5:state.skill==='advanced'?0:2;else if(a==='Cross-offshore')n+=state.sport==='kite'?4:state.sport==='sup'?3:0;if(d.gust-d.wind>=8)n+=2;return n>=4?'red':n>=2?'amber':'green'}
function markerIcon(colour){return L.divIcon({className:'',html:`<div class="spot-marker ${colour}"><span></span></div>`,iconSize:[27,27],iconAnchor:[13,27]})}
function mapCard(id,colour){let s=spots[id],listed=!s.sports||s.sports.includes(state.sport),trip=s.trips?.[state.skill]||s.trips?.intermediate||s.trips?.beginner,patrol=rnliPatrolState(s,state.selectedTime?new Date(state.selectedTime):new Date());$('#mapType').textContent=((s.region?`${s.region} · `:'')+`${s.type} launch`).toUpperCase();$('#mapSpotName').textContent=s.name;$('#mapSignal').textContent=!listed?`${sports[state.sport]} not yet verified here`:colour==='grey'?'Loading forecast signal':colour==='green'?'Good for this profile':colour==='amber'?'Use extra caution':'Avoid for this profile';$('#mapSignalDot').className=colour;$('#mapAccess').textContent=s.access;$('#localIntel').innerHTML=`<span>LAUNCH-SIDE INTELLIGENCE</span><strong>${s.sea==null?'Inspect the exact get-in':`Open water: ${compass(s.sea)}`}</strong><small>${s.intel||'Zoom in and switch map layers to inspect roads, parking, shelter and the shoreline. Aerial imagery may be old; verify on arrival.'}</small>`;$('#sessionIdea').innerHTML=trip?`<span>${state.skill==='advanced'?'WEEKEND-WARRIOR MISSION':'SESSION IDEA'}</span><strong>${trip.title}</strong><small>${trip.detail}</small>`:`<span>SESSION IDEA</span><strong>${state.skill==='advanced'?'Search the nearby evidence pins':'Stay close to this launch'}</strong><small>${state.skill==='advanced'?'Switch sports and compare coast angles; only documented uses are surfaced.':'No documented route is loaded here yet. Do not invent a crossing from the shape of the map.'}</small>`;$('#rnliStatus').textContent=s.rnli?patrol.label:'No RNLI patrol data verified';$('#rnliDates').textContent=s.rnli?.dates||'This does not mean there is no local lifeguard service. Check live flags and the RNLI directory.';$('#rnliLink').href=s.rnli?.url||'https://rnli.org/find-my-nearest/lifeguarded-beaches'}
function chooseFromMap(id){if(!spots[id])return;state.spot=id;document.body.classList.remove('exploring');$('#spotSelect').value=id;state.checks.fill(0);state.hourly=[];state.outlook=[];$('.map-stage').classList.remove('card-hidden');$('#mapInfoToggle').textContent='Hide spot card';$('#mapInfoToggle').setAttribute('aria-expanded','true');mapCard(id,spots[id]._signal||'grey');map.flyTo([spots[id].lat,spots[id].lon],Math.max(map.getZoom(),13),{duration:.7});load()}
function setMapLayer(name){Object.values(mapLayers).forEach(l=>map.removeLayer(l));mapLayers[name].addTo(map);$$('.map-mode button').forEach(b=>b.classList.toggle('active',b.dataset.layer===name))}
function drawWindAtLaunch(){if(!map||!state.live)return;let s=spots[state.spot],d=state.live,html=`<div class="launch-wind" style="--wind:${(d.dir+180)%360}deg"><i>↑</i><b>${Math.round(d.wind)}</b><small>mph from ${compass(d.dir)}</small></div>`;if(windMarker)windMarker.remove();windMarker=L.marker([s.lat,s.lon],{icon:L.divIcon({className:'',html,iconSize:[76,76],iconAnchor:[38,38]}),zIndexOffset:1000}).addTo(map)}
function syncZoomButtons(){if(!map)return;$('#mapZoomIn').disabled=map.getZoom()>=map.getMaxZoom();$('#mapZoomOut').disabled=map.getZoom()<=map.getMinZoom()}
function initMap(){if(typeof L==='undefined')return;map=L.map('map',{zoomControl:false,minZoom:5,maxZoom:19,dragging:true,touchZoom:true,scrollWheelZoom:true}).setView([54.7,-4.1],5);mapLayers.roads=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'});mapLayers.aerial=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles © Esri'});mapLayers.terrain=L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{maxZoom:17,attribution:'© OpenStreetMap contributors · SRTM | OpenTopoMap'});setMapLayer('roads');Object.entries(spots).forEach(([id,s])=>{markers[id]=L.marker([s.lat,s.lon],{icon:markerIcon('grey'),title:s.name}).addTo(map).on('click',()=>chooseFromMap(id))});$$('.map-mode button').forEach(b=>b.onclick=()=>setMapLayer(b.dataset.layer));let zoomBy=delta=>map.setZoom(Math.max(map.getMinZoom(),Math.min(map.getMaxZoom(),map.getZoom()+delta)));let controls=document.querySelector('.map-zoom');$('#mapZoomIn').addEventListener('click',e=>{e.preventDefault();e.stopPropagation();zoomBy(1)});$('#mapZoomOut').addEventListener('click',e=>{e.preventDefault();e.stopPropagation();zoomBy(-1)});L.DomEvent.disableClickPropagation(controls);L.DomEvent.disableScrollPropagation(controls);map.on('zoomend',syncZoomButtons);syncZoomButtons()}
async function updateMapSignals(){if(!map)return;let entries=Object.entries(spots),lat=entries.map(([,s])=>s.lat).join(','),lon=entries.map(([,s])=>s.lon).join(','),future=Boolean(state.selectedTime);try{let endpoint=future?`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&hourly=wind_speed_10m,wind_direction_10m,wind_gusts_10m&forecast_days=7&timezone=Europe%2FLondon&wind_speed_unit=mph`:`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=wind_speed_10m,wind_direction_10m,wind_gusts_10m&wind_speed_unit=mph`,r=await fetch(endpoint),rows=await r.json();if(!Array.isArray(rows))rows=[rows];rows.forEach((x,i)=>{let [id,s]=entries[i],at=future?x.hourly?.time?.indexOf(state.selectedTime):-1,d=future&&at>=0?{wind:+x.hourly.wind_speed_10m[at],gust:+x.hourly.wind_gusts_10m[at],dir:+x.hourly.wind_direction_10m[at]}:{wind:+x.current?.wind_speed_10m,gust:+x.current?.wind_gusts_10m,dir:+x.current?.wind_direction_10m};if(!Number.isFinite(d.wind))return;let colour=signalFor(s,d);s._signal=colour;markers[id]?.setIcon(markerIcon(colour))});mapCard(state.spot,spots[state.spot]._signal||'grey')}catch(e){}}
function fillSpots(){let groups={coast:'Coastal launches',harbour:'Harbours & estuaries',estuary:'Harbours & estuaries',reservoir:'Managed reservoirs',lake:'Lakes',river:'Rivers'};let used=new Set;$('#spotSelect').innerHTML='<option value="">Choose a beach or inland water…</option>'+Object.entries(groups).map(([type,label])=>{if(used.has(label))return'';used.add(label);let types=label==='Harbours & estuaries'?['harbour','estuary']:[type];return`<optgroup label="${label}">${Object.entries(spots).filter(([,s])=>types.includes(s.type)).sort((a,b)=>a[1].name.localeCompare(b[1].name)).map(([k,s])=>`<option value="${k}">${s.name}</option>`).join('')}</optgroup>`}).join('');$('#spotSelect').value=state.spot||''}
async function load(){const s=spots[state.spot],btn=$('#refreshButton');btn.disabled=true;btn.className='demo-pill live-pill';$('#liveStatus').textContent='Updating live data…';state.live=null;render();try{
let wurl=`https://api.open-meteo.com/v1/forecast?latitude=${s.lat}&longitude=${s.lon}&current=wind_speed_10m,wind_direction_10m,wind_gusts_10m,precipitation&hourly=wind_speed_10m,wind_direction_10m,wind_gusts_10m,precipitation&daily=sunrise,sunset&wind_speed_unit=mph&past_days=1&forecast_days=7&timezone=Europe%2FLondon`, req=[fetch(wurl)];if(['coast','harbour','estuary'].includes(s.type))req.push(fetch(`https://marine-api.open-meteo.com/v1/marine?latitude=${s.lat}&longitude=${s.lon}&hourly=wave_height,wave_period,sea_level_height_msl&past_days=1&forecast_days=7&timezone=Europe%2FLondon&cell_selection=sea`));let [wr,mr]=await Promise.all(req);if(!wr.ok)throw Error();let w=await wr.json(),m=mr?.ok?await mr.json():null,now=Date.now(),wi=w.hourly.time.reduce((b,x,i)=>Math.abs(new Date(x)-now)<Math.abs(new Date(w.hourly.time[b])-now)?i:b,0),mi=m?m.hourly.time.reduce((b,x,i)=>Math.abs(new Date(x)-now)<Math.abs(new Date(m.hourly.time[b])-now)?i:b,0):0,rain24=w.hourly.precipitation.slice(Math.max(0,wi-24),wi+1).reduce((a,b)=>a+(b||0),0),sea=m?.hourly?.sea_level_height_msl||[],trend=sea.length&&mi>0?sea[mi]-sea[mi-1]:null;
state.sun=(w.daily?.time||[]).map((date,i)=>({date,rise:new Date(w.daily.sunrise[i]),set:new Date(w.daily.sunset[i])}));state.currentLive={wind:+w.current.wind_speed_10m,gust:+w.current.wind_gusts_10m,dir:+w.current.wind_direction_10m,angle:relation(+w.current.wind_direction_10m,s.sea),rain24,wave:m?.hourly?.wave_height?.[mi]??null,period:m?.hourly?.wave_period?.[mi]??null,level:sea[mi]??null,tideTrend:trend==null?null:trend>.02?'Rising':trend<-.02?'Falling':'Near turn',updated:w.current.time};state.allHours=w.hourly.time.slice(wi).map((t,n)=>{let i=wi+n,marineIndex=m?.hourly?.time?.indexOf(t)??-1;return{time:t,wind:w.hourly.wind_speed_10m[i],gust:w.hourly.wind_gusts_10m[i],dir:w.hourly.wind_direction_10m[i],rain:w.hourly.precipitation[i],rain24,wave:marineIndex>=0?m.hourly.wave_height?.[marineIndex]??null:null,period:marineIndex>=0?m.hourly.wave_period?.[marineIndex]??null:null,angle:relation(w.hourly.wind_direction_10m[i],s.sea),updated:t}});state.hourly=state.allHours.slice(0,36);let days={};state.allHours.forEach(h=>{let key=h.time.slice(0,10);if(isDaylight(h.time))(days[key]??=[]).push(h)});state.outlook=Object.entries(days).slice(0,7).map(([date,hours])=>{let best=hours.reduce((a,b)=>windFit(b.wind).n<windFit(a.wind).n?b:a),winds=hours.map(h=>h.wind),gusts=hours.map(h=>h.gust);return{date,...best,minWind:Math.min(...winds),maxWind:Math.max(...winds),maxGust:Math.max(...gusts)}});let selected=state.selectedTime&&state.allHours.find(h=>h.time===state.selectedTime);state.live=selected||state.currentLive;if(!selected)state.selectedTime=null;btn.className='demo-pill live-pill live';$('#liveStatus').textContent=selected?`Forecast · ${new Date(selected.time).toLocaleDateString('en-GB',{weekday:'short'})} ${time(selected.time)}`:`Live · ${time(w.current.time)}`;render();drawWindAtLaunch()}catch(e){btn.className='demo-pill live-pill error';$('#liveStatus').textContent='Feed unavailable · retry';toast('Live feed unavailable. Retry in a moment.')}finally{btn.disabled=false}}
function windFit(speed){let b=state.skill==='beginner',a=state.skill==='advanced';if(state.sport==='sup')return speed>(b?12:a?25:18)?{n:4,title:'Too windy for this SUP profile'}:speed>(b?8:a?18:13)?{n:2,title:'Wind will make the return demanding'}:{n:0,title:'A manageable SUP wind'};if(state.sport==='wing')return speed<(b?10:a?15:12)?{n:4,title:'Too light for winging'}:speed<(b?14:a?18:16)?{n:2,title:'Marginal wing power'}:speed>(b?25:a?40:32)?{n:4,title:'Too strong for this wing profile'}:speed>(b?20:a?34:28)?{n:2,title:'Powered wing conditions'}:{n:0,title:a?'Charger wing window':'A usable wing window'};if(state.sport==='windsurf')return b?(speed<4?{n:4,title:'Too light even for learning'}:speed<7?{n:2,title:'Very light learning wind'}:speed<=14?{n:0,title:'Sub-planing learning conditions'}:speed<=18?{n:2,title:'Fresh learning conditions'}:{n:4,title:'Too strong for a learner'}):a?(speed<16?{n:4,title:'Below charger range'}:speed<19?{n:2,title:'Marginal powered wind'}:speed<=35?{n:0,title:'Full-power charger conditions'}:speed<=40?{n:2,title:'Severe expert-only wind'}:{n:4,title:'Extreme wind'}):(speed<11?{n:4,title:'Too light to plane'}:speed<13?{n:2,title:'Marginal planing wind'}:speed<=25?{n:0,title:'F4+ planing conditions'}:speed<=30?{n:2,title:'Strong advanced conditions'}:{n:4,title:'Extreme wind'});return speed<(b?12:a?15:10)?{n:4,title:'Too light for reliable kiting'}:speed<(b?15:a?18:13)?{n:2,title:'Marginal kite wind'}:speed>(b?27:a?40:32)?{n:4,title:'Too strong for this kite profile'}:speed>(b?22:a?34:28)?{n:2,title:'Powered kite conditions'}:{n:0,title:a?'Charger kite window':'A usable kite window'}}
function risk(){if(!state.live)return'amber';let d=state.live,s=spots[state.spot];if(s.sports&&!s.sports.includes(state.sport))return'amber';if(s.type==='river'&&s.gaugeValidated!==true)return'amber';let n=windFit(d.wind).n;if(s.type==='river'){if(d.rain24>=15)n+=5;else if(d.rain24>=7)n+=3;else if(d.rain24>=3)n++}else{if(d.angle==='Offshore')n+=state.sport==='sup'||state.sport==='kite'?5:3;else if(d.angle==='Cross-offshore')n+=state.sport==='kite'?4:state.sport==='sup'?3:1;if(d.wave>1.2&&state.sport==='sup'&&state.skill!=='advanced')n+=3;if(s.tide==='high'&&d.tideTrend==='Rising')n++;if(s.tide==='high'&&d.tideTrend==='Falling'&&['Offshore','Cross-offshore'].includes(d.angle))n+=3}if(d.gust-d.wind>=8)n+=2;return n>=4?'red':n>=2?'amber':'green'}
function words(level){let d=state.live,s=spots[state.spot],begin=state.skill==='beginner',fit=d?windFit(d.wind):null;if(!d)return{label:'Connecting',title:'Reading the latest models',copy:'Live conditions will appear in a moment.',advice:'Wait for the update before deciding.'};if(s.sports&&!s.sports.includes(state.sport))return{label:'Local confirmation needed',title:`${sports[state.sport]} is not verified here`,copy:'The water may look usable, but access, launch space, depth or local rules have not been confirmed for this sport.',advice:'Do not treat the weather signal as permission. Check the named operator, club or access authority first.'};if(s.type==='river'&&s.gaugeValidated!==true)return{label:'Research lead only',title:'No validated river range is loaded',copy:'The place may have documented paddling, but this stretch does not yet have human-checked gauge thresholds for a safe recommendation.',advice:'Do not use the app verdict to launch here. Check the official gauge, recent rain and a local operator.'};if(s.type==='river'&&d.rain24>=15)return{label:'Avoid this river',title:'Heavy rain raises the risk',copy:`About ${d.rain24.toFixed(0)} mm fell in the model grid over 24 hours. Fast flow, debris and changing levels may follow.`,advice:'Do not use rainfall alone—check the official gauge and local operator before launching.'};if(d.angle==='Offshore'&&['sup','kite'].includes(state.sport))return{label:'Choose another launch',title:'Offshore wind from this shore',copy:`${compass(d.dir)} wind is blowing away from this exact launch. Another side of a large lake may reverse that relationship.`,advice:`Compare ${s.alt}, then confirm parking, get-in and local conditions.`};if(fit.n>=4)return{label:fit.title.includes('light')?'Not enough wind':'Choose another session',title:fit.title,copy:`The live model shows ${Math.round(d.wind)} mph, gusting ${Math.round(d.gust)}. That sits outside the useful range for ${begin?'this learning profile':`powered ${sports[state.sport]} sailing`}.`,advice:fit.title.includes('light')?'Wait for a stronger window; board, sail, wing and rider weight still matter.':'Step down the session or wait for the wind to ease.'};if(level==='green')return{label:'Good window',title:fit.title,copy:`${compass(d.dir)} ${Math.round(d.wind)} mph${s.sea!=null?` is ${d.angle.toLowerCase()} from this launch`:''}${d.wave!=null?`, with ${d.wave.toFixed(1)} m waves`:''}.`,advice:s.sea!=null?'Zoom into the shoreline before travel; trees, cliffs and buildings can make the real wind gustier than the model.':'Stay within the permitted zone and keep your return route short.'};return{label:'Take care',title:fit.title,copy:`Wind is ${Math.round(d.wind)} mph, gusting ${Math.round(d.gust)}${s.type==='river'?`; 24-hour rain is ${d.rain24.toFixed(1)} mm`:''}.`,advice:'Check equipment range, the water itself, local notices and the operator before committing.'}}
function isDaylight(t){let x=new Date(t),day=state.sun.find(d=>d.date===String(t).slice(0,10));if(!day)return true;let session=state.mode==='paddle'?(state.skill==='beginner'?90:state.skill==='advanced'?150:120):90,margin=state.skill==='beginner'?45:30,latest=new Date(day.set.getTime()-(session+margin)*60000);return x>=day.rise&&x<=latest}
function windModeChoice(){let oldSport=state.sport,oldSkill=state.skill,s=spots[state.spot],choices=['wing','windsurf','kite'].filter(x=>!s.sports||s.sports.includes(x));if(!choices.length)return'wing';let ranked=choices.map(x=>{state.sport=x;state.skill=state.skills[x]||'beginner';let n=state.live?windFit(state.live.wind).n:4,a=state.live?.angle;if(x==='kite'&&['Offshore','Cross-offshore'].includes(a))n+=6;if(x==='wing'&&a==='Cross-offshore'&&state.skill==='advanced')n-=.5;return{x,n}}).sort((a,b)=>a.n-b.n);state.sport=oldSport;state.skill=oldSkill;return ranked[0].x}
function render(){state.sport=state.freeSport||state.sport||'sup';state.mode=state.sport==='sup'?'paddle':'wind';state.skill=state.skills?.[state.sport]||'beginner';let s=spots[state.spot],d=state.live||{wind:0,gust:0,dir:0,angle:'Loading',rain24:0,wave:null,period:null,level:null,tideTrend:null},level=risk(),w=words(level);$('#verdictCard').className=`verdict-card ${level}`;$('#verdictLabel').textContent=w.label;$('#verdictTitle').textContent=w.title;$('#verdictCopy').textContent=w.copy;$('#adviceText').innerHTML=`<strong>Local signal:</strong> ${w.advice}`;$('#windSpeed').textContent=state.live?Math.round(d.wind):'–';$('#windDir').textContent=state.live?compass(d.dir):'—';$('#gustText').textContent=state.live?`gusts ${Math.round(d.gust)}`:'connecting';$('#windArrow').style.transform=`rotate(${(d.dir+180)%360}deg)`;$('.time-label').textContent=state.selectedTime?`${new Date(state.selectedTime).toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'short'})} · ${time(state.selectedTime)}`:'Current model hour';$('#altName').textContent=s.alt;$('#altMeta').textContent=s.meta;$('#skillQuick').textContent=state.skill[0].toUpperCase()+state.skill.slice(1);$$('.activity-picker button').forEach(b=>b.classList.add('active'));
let selectedDate=state.selectedTime?.slice(0,10),raw=selectedDate?state.allHours.filter(h=>h.time.slice(0,10)===selectedDate):state.hourly.length?state.hourly:Array.from({length:12},(_,i)=>({time:new Date(Date.now()+i*36e5),wind:0,gust:0,dir:0})),hs=state.sun.length?raw.filter(h=>isDaylight(h.time)).slice(0,16):raw.slice(0,16),valid=hs.filter(h=>h.wind>0),quiet=valid.reduce((a,b)=>b.wind<a.wind?b:a,valid[0]||{wind:0,time:new Date()}),strong=valid.reduce((a,b)=>b.wind>a.wind?b:a,valid[0]||{wind:0,time:new Date()}),usable=valid.filter(h=>windFit(h.wind).n===0),best=usable[Math.floor(usable.length/2)]||valid[Math.floor(valid.length/2)]||quiet;$('.hourly .eyebrow').textContent=selectedDate?new Date(selectedDate+'T12:00').toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'short'}).toUpperCase():'TODAY’S WINDOW';$('#windInsights').innerHTML=`<div><span>DAYLIGHT QUIETEST</span><strong>${quiet.wind?Math.round(quiet.wind)+' mph · '+time(quiet.time):'Loading…'}</strong></div><div><span>DAYLIGHT STRONGEST</span><strong>${strong.wind?Math.round(strong.wind)+' mph · '+time(strong.time):'Loading…'}</strong></div><div><span>BEST DAYLIGHT ${state.mode==='wind'?sports[state.sport].toUpperCase():'SUP'} WINDOW</span><strong>${best.wind?time(best.time)+' · '+Math.round(best.wind)+' mph':'No daylight window loaded'}</strong></div>`;$('#hourStrip').innerHTML=hs.map((h,i)=>`<div class="hour ${!selectedDate&&i===0?'now':''} ${h.time===state.selectedTime||h===best?'best':''}"><span>${time(h.time)}</span><i style="transform:rotate(${(h.dir+180)%360}deg);--gust:${Math.min(1.35,1+(h.gust-h.wind)/30)}">↑</i><b>${h.wind?Math.round(h.wind):'–'}</b><small>${h.gust?`gust ${Math.round(h.gust)}`:'mph'}</small></div>`).join('');let marine=state.marine;$('#detailGrid').innerHTML=`<div><span>${state.mode==='wind'?'Best wind-sport match':s.sea!=null?'Wind vs shoreline':'Water type'}</span><strong>${state.mode==='wind'?sports[state.sport]:s.sea!=null?d.angle:s.type}</strong></div><div><span>${s.type==='river'?'Rain, past 24h':'Surf / swell pulse'}</span><strong>${s.type==='river'?d.rain24.toFixed(1)+' mm':d.wave!=null?`${d.wave.toFixed(1)} m total sea${d.period?` · ${Math.round(d.period)} sec`:''}`:'Not applicable'}</strong></div><div><span>${s.tide==='none'?'Access':'Tide / broad current'}</span><strong>${s.tide==='none'?'Managed / local rules':marine?.currentSpeed!=null?`${marine.currentSpeed.toFixed(1)} kn toward ${compass(marine.currentDir)} · ${d.tideTrend||'trend unavailable'}`:d.tideTrend||'Unavailable'}</strong></div>`;
$('#outlookStrip').innerHTML=state.outlook.length?state.outlook.map(o=>{let fit=windFit(o.wind),sig=signalFor(s,o),day=new Date(o.date+'T12:00').toLocaleDateString('en-GB',{weekday:'short'}),selected=o.time===state.selectedTime;return`<button type="button" class="outlook-day ${sig} ${selected?'selected':''}" data-forecast-time="${o.time}" aria-pressed="${selected}"><span>${day}</span><b>${Math.round(o.minWind)}–${Math.round(o.maxWind)} mph</b><small>Best: ${time(o.time)} · ${Math.round(o.wind)} mph ${compass(o.dir)}</small><small>Peak gust ${Math.round(o.maxGust)} mph</small></button>`}).join(''):'<div class="outlook-loading">Building the seven-day travel picture…</div>';let rs=[{tone:s.sea!=null?(d.angle==='Offshore'?'bad':d.angle==='Cross-offshore'?'warn':'good'):'good',name:s.sea!=null?'Wind vs geography':'Venue type',status:s.sea!=null?d.angle:s.type,desc:s.sea!=null?`Open water lies ${compass(s.sea)} from this launch.`:s.access},{tone:d.wind>15?'warn':'good',name:'Wind and gusts',status:state.live?`${Math.round(d.wind)} → ${Math.round(d.gust)} mph`:'—',desc:d.gust-d.wind>=8?'Gust spread may affect control.':'The model shows a steadier spread.'},{tone:s.type==='river'&&d.rain24>=7?'bad':'good',name:s.type==='river'?'Rain/runoff':'Access signal',status:s.type==='river'?`${d.rain24.toFixed(1)} mm`:'Check locally',desc:s.type==='river'?'Rain is a proxy only; confirm river gauge and operator advice.':s.access}];$('#reasonList').innerHTML=rs.map(r=>`<div class="reason ${r.tone}"><div class="reason-top"><strong>${r.name}</strong><span>${r.status}</span></div><p>${r.desc}</p></div>`).join('');checks()}
const items=['I have the sport-appropriate leash and buoyancy aid','Someone knows my route and return time','I’m not going out alone','I checked access rules, local notices and the water','I found hazards, my safe exit and how I would signal for help'];function checks(){$('#checklistItems').innerHTML=items.map((x,i)=>`<label class="check-row"><input type="checkbox" data-check="${i}" ${state.checks[i]?'checked':''}><span class="fake-check"></span><span>${x}</span></label>`).join('');let n=state.checks.filter(Boolean).length;$('#progress').textContent=`${n} / ${items.length}`;$('#checkNote').textContent=n===items.length?'All checked. Pause once more at the water’s edge.':'Tick every item before you get on the water.';$('#checkNote').classList.toggle('complete',n===items.length)}
function toast(x){let t=$('#toast');t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}function openSetup(){['paddle','wind'].forEach(mode=>{let input=$(`#setupForm input[name="skill_${mode==='paddle'?'sup':'wind'}"][value="${state.skills?.[mode]||'beginner'}"]`);if(input)input.checked=true});$('#setupDialog').showModal()}function save(){let f=new FormData($('#setupForm'));state.skills={paddle:f.get('skill_sup')||'beginner',wind:f.get('skill_wind')||'beginner'};state.skill=state.skills[state.mode];state.profile={leash:f.has('leash'),pfd:f.has('pfd'),comms:f.has('comms'),training:f.has('training'),solo:f.has('solo')};localStorage.setItem('shorewise-profile-v3',JSON.stringify({mode:state.mode,skills:state.skills,profile:state.profile,setupComplete:true}));render();toast(`SUP: ${state.skills.paddle} · wind sports: ${state.skills.wind}`)}
$('#spotSelect').onchange=e=>{state.spot=e.target.value;state.checks.fill(0);state.hourly=[];state.marine=null;state.selectedTime=null;mapCard(state.spot,spots[state.spot]._signal||'grey');map?.flyTo([spots[state.spot].lat,spots[state.spot].lon],8);load()};$$('.activity-picker button').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;state.skill=state.skills[state.mode];state.sport=state.mode==='paddle'?'sup':windModeChoice();render();updateMapSignals()});$('#refreshButton').onclick=()=>{state.selectedTime=null;load();updateMapSignals()};$('#profileButton').onclick=openSetup;$('#skillQuick').onclick=openSetup;$('#setupForm').onsubmit=()=>{save();updateMapSignals()};$('#outlookStrip').onclick=e=>{let button=e.target.closest('[data-forecast-time]');if(!button)return;state.selectedTime=button.dataset.forecastTime;let selected=state.allHours.find(h=>h.time===state.selectedTime);if(!selected)return;state.live=selected;$('#liveStatus').textContent=`Forecast · ${new Date(selected.time).toLocaleDateString('en-GB',{weekday:'short'})} ${time(selected.time)}`;render();drawWindAtLaunch();updateMapSignals()};$('#checklistItems').onchange=e=>{if(e.target.dataset.check!==undefined){state.checks[+e.target.dataset.check]=e.target.checked;checks()}};$('#detailToggle').onclick=()=>{let g=$('#detailGrid');g.hidden=!g.hidden;$('#detailToggle').textContent=g.hidden?'Show detail ⌄':'Hide detail ⌃'};$('#routeButton').onclick=()=>toast(`${spots[state.spot].alt}: confirm access and conditions before travel`);$('#openSpotButton').onclick=()=>$('#verdictCard').scrollIntoView({behavior:'smooth',block:'start'});
let hasSetup=false;try{let saved=JSON.parse(localStorage.getItem('shorewise-profile-v6'));if(saved?.setupComplete){state.freeSport=saved.freeSport||'sup';state.sport=state.freeSport;state.mode=state.sport==='sup'?'paddle':'wind';state.skills={...state.skills,...saved.skills};state.skill=state.skills[state.sport]||'beginner';state.profile=saved.profile;state.home=saved.home;hasSetup=true}}catch{}document.body.classList.add('exploring');fillSpots();initMap();

const baseWords=words;
words=function(level){let d=state.live,s=spots[state.spot];if(d&&s.tide==='high'&&d.tideTrend==='Falling'&&['Offshore','Cross-offshore'].includes(d.angle))return{label:'Wind and tide compound',title:'Both forces may take you away',copy:`The ${compass(d.dir)} wind is ${d.angle.toLowerCase()} and the modelled tide is falling. A light wind does not make an ebbing tidal venue beginner-friendly.`,advice:'Choose a sheltered launch, start against the combined force, and do not rely on being able to paddle back against it.'};return baseWords(level)};
if(document.modelContext?.registerTool)Promise.resolve(document.modelContext.registerTool({name:'check_live_conditions',title:'Check live conditions',description:'Fetch a live model signal for a curated UK and Ireland watersports launch.',inputSchema:{type:'object',properties:{spot:{type:'string',enum:Object.keys(spots)},sport:{type:'string',enum:Object.keys(sports)},skill:{type:'string',enum:['beginner','intermediate','advanced']}},required:['spot','sport','skill'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},async execute(x){if(!spots[x.spot]||!sports[x.sport]||!['beginner','intermediate','advanced'].includes(x.skill))throw Error('Unsupported selection');Object.assign(state,x);$('#spotSelect').value=x.spot;await load();return{spot:spots[x.spot].name,verdict:risk(),summary:words(risk()).title,wind_mph:state.live?.wind,shore_relation:state.live?.angle,rain_24h_mm:state.live?.rain24}}})).catch(()=>{});

const originalUpdateMapSignals=updateMapSignals;
updateMapSignals=async function(){Object.entries(spots).forEach(([id,s])=>{if(s.sports&&!s.sports.includes(state.sport)){s._signal='grey';markers[id]?.setIcon(markerIcon('grey'))}});if(!state.spot)return;mapCard(state.spot,spots[state.spot]._signal||'grey');return originalUpdateMapSignals()};

async function enrichMarine(){let s=spots[state.spot],box=$('#marineReadout');state.marine=null;if(!['coast','harbour','estuary'].includes(s.type)){box.innerHTML='<span>WATER MOVEMENT</span><strong>Gauge connection is the next data step</strong><small>Rainfall remains a warning proxy. Until a local safe range is validated, a river level must be information—not a green light.</small>';return}try{let r=await fetch(`https://marine-api.open-meteo.com/v1/marine?latitude=${s.lat}&longitude=${s.lon}&current=wave_height,wave_direction,wave_period,swell_wave_height,swell_wave_direction,swell_wave_period,ocean_current_velocity,ocean_current_direction&hourly=sea_level_height_msl&forecast_days=2&timezone=Europe%2FLondon&cell_selection=sea&wind_speed_unit=kn`),x=await r.json(),levels=x.hourly?.sea_level_height_msl||[],times=x.hourly?.time||[],turns=[];for(let i=1;i<levels.length-1;i++)if((levels[i]>=levels[i-1]&&levels[i]>levels[i+1])||(levels[i]<=levels[i-1]&&levels[i]<levels[i+1]))turns.push({high:levels[i]>levels[i-1],time:times[i]});let next=turns.filter(t=>new Date(t.time)>new Date()).slice(0,2).map(t=>`${t.high?'High':'Low'} ${time(t.time)}`).join(' · '),c=x.current||{},sea=c.wave_height==null?'Wave model unavailable':`${c.wave_height.toFixed(1)} m sea from ${compass(c.wave_direction)} · ${Math.round(c.wave_period||0)} sec`,swell=c.swell_wave_height==null?'swell split unavailable':`${c.swell_wave_height.toFixed(1)} m swell from ${compass(c.swell_wave_direction)} · ${Math.round(c.swell_wave_period||0)} sec`,current=c.ocean_current_velocity==null?'broad current unavailable':`${c.ocean_current_velocity.toFixed(1)} kn toward ${compass(c.ocean_current_direction)}`;state.marine={swellHeight:c.swell_wave_height,swellDir:c.swell_wave_direction,swellPeriod:c.swell_wave_period,currentSpeed:c.ocean_current_velocity,currentDir:c.ocean_current_direction};box.innerHTML=`<span>SURF / CHARGER PULSE</span><strong>${sea}</strong><small>${swell} · ${current}<br>${next||'Next tide turns unavailable'} · Current is an ~8 km model, not harbour, estuary or navigation advice.</small>`;render()}catch{box.innerHTML='<span>SURF / CHARGER PULSE</span><strong>Marine feed unavailable</strong><small>Check a local tide table and observation before travel.</small>'}}
async function loadMarineOverlay(){let s=spots[state.spot];if(waveMarker){waveMarker.remove();waveMarker=null}if(!map||!['coast','harbour','estuary'].includes(s.type))return;try{let r=await fetch(`https://marine-api.open-meteo.com/v1/marine?latitude=${s.lat}&longitude=${s.lon}&current=wave_height,wave_direction,wave_period&hourly=sea_level_height_msl&forecast_days=1&timezone=Europe%2FLondon&cell_selection=sea`),x=await r.json(),h=x.current?.wave_height,dir=x.current?.wave_direction,levels=x.hourly?.sea_level_height_msl||[],times=x.hourly?.time||[],now=Date.now(),i=times.reduce((b,t,n)=>Math.abs(new Date(t)-now)<Math.abs(new Date(times[b])-now)?n:b,0),trend=i>0?levels[i]-levels[i-1]:0,tide=trend>.02?'TIDE ↑':trend<-.02?'TIDE ↓':'TIDE TURN',html=`<div class="wave-marker" style="--wave:${dir||0}deg"><i>↑</i><b>${h==null?'SEA':h.toFixed(1)+'m WAVE'}</b><small>${dir==null?'direction unavailable':`from ${compass(dir)}`} · ${tide}</small></div>`;waveMarker=L.marker([s.lat,s.lon],{icon:L.divIcon({className:'',html,iconSize:[120,54],iconAnchor:[-42,27]}),zIndexOffset:900}).addTo(map)}catch{}}
const originalLoad=load;
load=async function(){await originalLoad();await Promise.all([enrichMarine(),loadMarineOverlay()])};
setTimeout(()=>{if(state.spot)enrichMarine()},1600);

const windGrid=[[-8,50],[-5,50],[-2,50],[1,50],[-8,52],[-5,52],[-2,52],[1,52],[-8,54],[-5,54],[-2,54],[1,54],[-8,56],[-5,56],[-2,56],[1,56],[-8,58],[-5,58],[-2,58],[1,58],[-8,60],[-5,60],[-2,60],[1,60]];
let windSamples=[],flowParticles=[];
async function loadWindField(){try{let lat=windGrid.map(p=>p[1]).join(','),lon=windGrid.map(p=>p[0]).join(','),r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=wind_speed_10m,wind_direction_10m&wind_speed_unit=mph`),rows=await r.json();if(!Array.isArray(rows))rows=[rows];windSamples=rows.map((x,i)=>({lon:windGrid[i][0],lat:windGrid[i][1],speed:+x.current.wind_speed_10m,dir:+x.current.wind_direction_10m}));startWindField()}catch{}}
function startWindField(){let c=$('#windField'),ctx=c.getContext('2d'),stage=c.parentElement,resize=()=>{c.width=stage.clientWidth*devicePixelRatio;c.height=stage.clientHeight*devicePixelRatio;c.style.width=stage.clientWidth+'px';c.style.height=stage.clientHeight+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);flowParticles=Array.from({length:120},()=>({x:Math.random()*stage.clientWidth,y:Math.random()*stage.clientHeight,age:Math.random()*70}))};resize();addEventListener('resize',resize);function frame(){let w=stage.clientWidth,h=stage.clientHeight;ctx.globalCompositeOperation='destination-out';ctx.fillStyle='rgba(0,0,0,.2)';ctx.fillRect(0,0,w,h);ctx.globalCompositeOperation='source-over';ctx.lineWidth=1.35;flowParticles.forEach(p=>{let ll=map.containerPointToLatLng([p.x,p.y]),v=windSamples.reduce((a,b)=>(Math.abs(b.lat-ll.lat)+Math.abs(b.lon-ll.lng))<(Math.abs(a.lat-ll.lat)+Math.abs(a.lon-ll.lng))?b:a),rad=(v.dir+90)*Math.PI/180,step=.28+v.speed/22,nx=p.x+Math.cos(rad)*step,ny=p.y+Math.sin(rad)*step;ctx.strokeStyle=`rgba(4,91,108,${.38+Math.min(.42,v.speed/55)})`;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(nx,ny);ctx.stroke();p.x=nx;p.y=ny;p.age++;if(p.x<0||p.x>w||p.y<0||p.y>h||p.age>85){p.x=Math.random()*w;p.y=Math.random()*h;p.age=0}});requestAnimationFrame(frame)}requestAnimationFrame(frame)}
loadWindField();

const originalMapCard=mapCard;
mapCard=function(id,colour){originalMapCard(id,colour);let s=spots[id],badge=$('#evidenceBadge'),link=$('#evidenceLink'),unvalidatedRiver=s.type==='river'&&s.gaugeValidated!==true;badge.textContent=unvalidatedRiver?'◌ RESEARCH LEAD — GAUGE RANGE NOT VALIDATED':s.evidence?`✓ ${s.evidence.toUpperCase()}`:s.source?'◐ PUBLISHED SOURCE':'◌ RESEARCH LEAD';badge.className=unvalidatedRiver?'lead':s.evidence?'verified':s.source?'sourced':'lead';link.hidden=!s.source;if(s.source)link.href=s.source};
if(state.spot)mapCard(state.spot,spots[state.spot]._signal||'grey');
const renderEvidence=render;
render=function(){renderEvidence();let s=spots[state.spot],target=Object.values(spots).find(x=>x.name===s.alt),strong=$('.alt-score strong'),small=$('.alt-score small'),tips={sup:'Stay within a distance you could genuinely swim. If wind wins, lie prone, secure the paddle under your chest and paddle across the wind toward the nearest safe shore.',windsurf:'Check the downwind landing before rigging. If you cannot identify a safe exit, the session has no proper Plan B.',wing:'Carry a board leash, wing leash and means of communication. Know how you will self-rescue with the wing depowered before launching.',kite:'Confirm a clear launch, landing and downwind exclusion zone. A green wind reading cannot make a cramped beach suitable for a kite.'};$('#buddyTip').textContent=tips[state.sport];if(target&&(target.evidence||target.source)){strong.textContent='Evidence-backed alternative';small.textContent=target.evidence||'Published location source available'}else{strong.textContent='Alternative needs verification';small.textContent='Weather comparison only — confirm access and sport use'}};
if(state.spot)render();

// Curated hazards are independent of broad forecast models. "Extreme" blocks a green
// beginner signal; hazard-only pins are never suggested as launches.
const forecastSignalFor=signalFor;
signalFor=function(s,d){if(s.hazardOnly)return'red';let result=forecastSignalFor(s,d);if(s.hazard?.severity==='extreme'&&state.skill!=='advanced')return'red';if(s.hazard?.severity==='high'&&result==='green')return'amber';return result};
const forecastRisk=risk;
risk=function(){let s=spots[state.spot];if(s?.hazardOnly)return'red';let result=forecastRisk();if(s?.hazard?.severity==='extreme'&&state.skill!=='advanced')return'red';if(s?.hazard?.severity==='high'&&result==='green')return'amber';return result};
const forecastWords=words;
words=function(level){let s=spots[state.spot],h=s?.hazard;if(s?.hazardOnly)return{label:'Hazard reference — do not launch',title:h.title,copy:h.copy,advice:'Use the source link and seek qualified local guidance. Shorewise will not turn model weather into a go signal here.'};if(h?.severity==='extreme'&&state.skill!=='advanced')return{label:'Local hazard overrides forecast',title:h.title,copy:h.copy,advice:'Choose a different water or go with a qualified local provider. A favourable wind colour is not enough.'};return forecastWords(level)};
const evidenceMapCard=mapCard;
mapCard=function(id,colour){evidenceMapCard(id,colour);let s=spots[id],h=s.hazard,card=$('#hazardCard');if(s.hazardOnly){$('#mapType').textContent=`${s.region||''} · HAZARD REFERENCE`.toUpperCase();$('#mapSignal').textContent='Never auto-recommended';$('#sessionIdea').innerHTML='<span>SAFER PLAN</span><strong>Choose a different venue</strong><small>This pin exists to warn you, not to advertise a launch or route.</small>'}card.hidden=!h;if(!h)return;card.className=`hazard-card ${h.severity==='extreme'?'severe':''}`;$('#hazardTitle').textContent=h.title;$('#hazardCopy').textContent=h.copy;$('#hazardLink').href=h.source||s.source||'#'};
if(state.spot)mapCard(state.spot,spots[state.spot]._signal||'grey');

// A neutral map is the home state; forecasts only begin after a real place is chosen.
$('#spotSelect').onchange=e=>{if(e.target.value)chooseFromMap(e.target.value)};
$$('.activity-picker button').forEach(button=>button.onclick=()=>{state.mode=button.dataset.mode;$$('.activity-picker button').forEach(b=>b.classList.toggle('active',b===button));if(!state.spot)return;state.sport=state.mode==='paddle'?'sup':windModeChoice();render();updateMapSignals()});
$('#refreshButton').onclick=()=>{if(!state.spot)return toast('Choose a pin or location first');state.selectedTime=null;load();updateMapSignals()};

// Profile v4 keeps ability separate for each discipline while retaining the compact two-mode UI.
openSetup=function(){let sup=$(`#setupForm input[name="skill_sup"][value="${state.skills?.sup||state.skills?.paddle||'beginner'}"]`);if(sup)sup.checked=true;['wing','windsurf','kite'].forEach(sport=>{let input=$(`#setupForm select[name="skill_${sport}"]`);if(input)input.value=state.skills?.[sport]||state.skills?.wind||'beginner'});$('#setupDialog').showModal()};
save=function(){let f=new FormData($('#setupForm'));state.skills={sup:f.get('skill_sup')||'beginner',wing:f.get('skill_wing')||'beginner',windsurf:f.get('skill_windsurf')||'beginner',kite:f.get('skill_kite')||'beginner'};state.skills.paddle=state.skills.sup;state.skills.wind=state.skills[state.sport]||state.skills.wing;state.skill=state.skills[state.sport]||'beginner';state.profile={leash:f.has('leash'),pfd:f.has('pfd'),comms:f.has('comms'),training:f.has('training'),solo:f.has('solo')};localStorage.setItem('shorewise-profile-v4',JSON.stringify({mode:state.mode,skills:state.skills,profile:state.profile,setupComplete:true}));render();toast('Saved separate SUP, wing, windsurf and kite levels')};
$('#profileButton').onclick=openSetup;$('#skillQuick').onclick=openSetup;
const renderPerDiscipline=render;
render=function(){state.sport=state.freeSport||state.sport||'sup';state.mode=state.sport==='sup'?'paddle':'wind';state.skills.paddle=state.skills.sup||'beginner';state.skills.wind=state.skills[state.sport]||'beginner';state.skill=state.skills[state.sport]||'beginner';renderPerDiscipline()};
$('#mapInfoToggle').onclick=()=>{let stage=$('.map-stage'),hidden=stage.classList.toggle('card-hidden'),button=$('#mapInfoToggle');button.textContent=hidden?'Show spot card':'Hide spot card';button.setAttribute('aria-expanded',String(!hidden));setTimeout(()=>map?.invalidateSize(),220)};

let smartAlternativeId=null;
function milesBetween(a,b){const r=3958.8,p=Math.PI/180,dLat=(b.lat-a.lat)*p,dLon=(b.lon-a.lon)*p,x=Math.sin(dLat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dLon/2)**2;return 2*r*Math.asin(Math.sqrt(x))}
function exposureOf(s){if(Number.isFinite(s.exposure))return s.exposure;if(['lake','reservoir','river'].includes(s.type))return 0;if(['harbour','estuary'].includes(s.type))return 1;return 3}
const roadCache=new Map(),roadPending=new Set();
function smartAlternative(){let here=spots[state.spot],live=state.live,named=Object.entries(spots).find(([,s])=>s.name===here.alt)?.[0],hereExposure=exposureOf(here),local=new Map((here.localAlternatives?.[state.sport]||[]).map(x=>[x.id,x])),candidates=Object.entries(spots).filter(([id,s])=>id!==state.spot&&s.sports?.includes(state.sport)&&(s.evidence||s.source)&&!(s.type==='river'&&s.gaugeValidated!==true)).map(([id,s])=>{let distance=milesBetween(here,s),signal=s._signal||(live?signalFor(s,live):'grey'),localRule=local.get(id),distanceScore=distance<=15?65:distance<=30?42:distance<=50?15:-80,score=(signal==='green'?80:signal==='amber'?43:signal==='grey'?18:-25)+distanceScore;score+=s.evidence?13:6;if(id===named&&distance<=50)score+=12;if(localRule)score+=localRule.priority||20;if(live?.wave>=1.2&&exposureOf(s)<hereExposure)score+=(hereExposure-exposureOf(s))*18;if(state.skill==='beginner'&&exposureOf(s)>=3)score-=18;if(state.sport==='sup'&&['lake','reservoir'].includes(s.type)&&s.evidence)score+=12;if(state.sport==='sup'&&state.skill==='beginner'&&rnliPatrolState(s).active)score+=18;return{id,s,distance,signal,score,distanceScore,minutes:localRule?.minutes,note:localRule?.note}}).filter(x=>x.distance<=50&&(x.signal!=='red'||state.sport==='sup'&&['lake','reservoir'].includes(x.s.type))).sort((a,b)=>b.score-a.score);let winner=candidates[0]||null;if(winner)winner.shortlist=candidates.slice(0,5);return winner}
function alternativeReason(choice){let here=spots[state.spot],s=choice.s,bits=[];if(state.live){let currentRel=relation(state.live.dir,here.sea),nextRel=relation(state.live.dir,s.sea);if(['Offshore','Cross-offshore'].includes(currentRel)&&!['Offshore','Cross-offshore'].includes(nextRel))bits.push('safer wind angle');if(state.live.wave>=1.2&&exposureOf(s)<exposureOf(here))bits.push('more shelter from swell')}if(['lake','reservoir'].includes(s.type)&&['coast','harbour','estuary'].includes(here.type))bits.push('managed inland fallback');if(s.evidence)bits.push('documented local use');else bits.push('published location source');let journey=Number.isFinite(choice.minutes)?`about ${choice.minutes} min drive`:'road time not checked';return `${journey} · ${bits.slice(0,2).join(' · ')||choice.note||'different launch orientation'}`}
function roadKey(){return`${state.spot}|${state.sport}|${state.skill}|${state.selectedTime||'now'}`}
async function refineRoadAlternative(shortlist,key){if(!shortlist?.length||roadPending.has(key))return;roadPending.add(key);let here=spots[state.spot],coords=[[here.lon,here.lat],...shortlist.map(x=>[x.s.lon,x.s.lat])].map(x=>x.join(',')).join(';'),destinations=shortlist.map((_,i)=>i+1).join(';');try{let response=await fetch(`https://router.project-osrm.org/table/v1/driving/${coords}?sources=0&destinations=${destinations}`),json=await response.json(),durations=json?.durations?.[0]||[];let routed=shortlist.map((choice,i)=>({...choice,minutes:Number.isFinite(durations[i])?Math.round(durations[i]/60):choice.minutes})).filter(choice=>Number.isFinite(choice.minutes)&&choice.minutes<=60).map(choice=>({...choice,roadScore:choice.score-choice.distanceScore+(choice.minutes<=20?65:choice.minutes<=40?42:15)})).sort((a,b)=>b.roadScore-a.roadScore);roadCache.set(key,routed[0]||null)}catch(error){roadCache.set(key,null)}finally{roadPending.delete(key);if(key===roadKey())paintAlternative(roadCache.get(key),false,true)}}
function arrivalTip(){let s=spots[state.spot],d=state.live;if(d&&['Offshore','Cross-offshore'].includes(d.angle))return'Offshore wind? Don’t launch. Find a shore where it blows in or across.';if(s.type==='river')return'Fast flow, debris or rising water? Walk away.';if(s.type==='coast'&&d?.wave>=1)return'Watch three full sets. Find rips, rocks and a second exit.';if(state.sport==='sup')return'Stay within swimming distance. Blown away? Lie down and paddle diagonally to shore.';return'Before rigging, find your downwind exit.'}
function paintAlternative(choice,pending=false,routeChecked=false){let strong=$('.alt-score strong'),small=$('.alt-score small'),orb=$('.mini-orb');smartAlternativeId=choice?.id||null;$('#buddyTip').textContent=arrivalTip();if(!choice){$('#altName').textContent='No credible match within about an hour';$('#altMeta').textContent=routeChecked?'No road-time-qualified alternative found':'Check the map manually or change sport/profile';strong.textContent='No automatic redirect';small.textContent='A distant famous venue is not being presented as “nearby”';orb.textContent='—';return}$('#altName').textContent=choice.s.name;$('#altMeta').textContent=pending?'Checking actual road time…':alternativeReason(choice);strong.textContent=choice.signal==='green'?'Stronger local match for this profile':choice.signal==='red'?'Contained-water fallback — still not recommended in this wind':'Local option worth comparing';small.textContent=choice.s.intel||choice.s.access;orb.textContent=pending?'…':choice.signal==='green'?'✓':'!'}
function renderSmartAlternative(){let key=roadKey(),choice=smartAlternative();if(roadCache.has(key)){paintAlternative(roadCache.get(key),false,true);return}paintAlternative(choice,Boolean(choice),false);if(choice)refineRoadAlternative(choice.shortlist,key)}
const renderAlternatives=render;
render=function(){renderAlternatives();renderSmartAlternative()};
$('#routeButton').onclick=()=>{if(!smartAlternativeId)return toast('No evidence-backed nearby match for this sport and profile');chooseFromMap(smartAlternativeId);document.querySelector('.map-panel')?.scrollIntoView({behavior:'smooth',block:'start'})};
if(state.spot)render();

// V6 tester experience: one sport plus a local free area, with sport-specific readiness checks.
Object.assign(spots.tynemouth,{localAlternatives:{sup:[{id:'killingworth',minutes:18,priority:45,note:'restricted council lake; permission and qualification required'},{id:'qe2_lake',minutes:24,priority:42,note:'council-permitted inland water'},{id:'ladyburn',minutes:35,priority:38,note:'bookable sheltered-water centre and permit venue'}]}});

const FREE_RADIUS_MILES=35;
const readiness={
sup:{kit:[['right_leash','Correct leash for this water'],['buoyancy','Buoyancy aid for touring/open water'],['comms','Waterproof phone or VHF'],['buddy','I plan to paddle with someone']],ability:[['self_rescue','I can climb back on unaided'],['prone_return','I can lie down and paddle to shore'],['conditions','I recognise offshore wind and moving water']],awards:[['none','No formal award'],['lesson','Lesson with a qualified instructor'],['paddle_start','Paddle UK Start / Discover'],['paddle_explore','Paddle UK Explore or discipline award']]},
wing:{kit:[['board_leash','Board leash'],['wing_leash','Wing leash'],['impact','Impact vest / buoyancy aid'],['helmet','Helmet for foiling or harder conditions'],['buddy','I avoid sailing alone']],ability:[['self_rescue','I can depower and self-rescue'],['upwind','I can hold ground and return upwind'],['foil_control','I can fall clear and control the foil']],awards:[['none','No formal award'],['lesson','Lesson with a qualified instructor'],['learn_wing','RYA Learn / Improve Your Wingsurfing'],['first_flights','RYA Wingfoiling First Flights'],['sustained','RYA Wingfoiling Sustained Flights']]},
windsurf:{kit:[['exposure','Suitable wetsuit / exposure protection'],['harness','Harness with correctly set lines'],['helmet','Helmet for waves, foiling or harder conditions'],['comms','Waterproof means of calling for help'],['buddy','I avoid sailing alone in stronger wind']],ability:[['self_rescue','I can uphaul or self-rescue'],['harness_skill','I can use the harness confidently'],['planing','I can plane and use footstraps'],['return','I can return to my launch in changing wind']],awards:[['none','No formal award'],['lesson','Lesson with a qualified instructor'],['rya_start','RYA Start Windsurfing'],['rya_intermediate','RYA Intermediate (non-planing)'],['rya_planing','RYA Intermediate (planing)'],['rya_advanced','RYA Advanced / foiling course']]},
kite:{kit:[['helmet','Helmet'],['impact','Impact vest / flotation harness'],['release','Tested quick-release system'],['comms','Waterproof means of calling for help'],['buddy','Buddy launch / land and never alone']],ability:[['self_rescue','I can self-rescue and pack down'],['relaunch','I can relaunch in deep water'],['upwind','I can ride upwind and return'],['weather','I understand launch zones and squalls']],awards:[['none','No formal award'],['lesson','Lesson with a recognised kite school'],['independent','Signed off as an independent rider'],['advanced','Advanced coaching / rescue training']]}
};

function renderReadiness(sport=state.freeSport||'sup'){let config=readiness[sport]||readiness.sup,profile=state.profile||{},chosen=new Set(profile.readiness||[]);$('#sportKit').innerHTML=config.kit.map(([value,label])=>`<label><input type="checkbox" name="readiness" value="${value}" ${chosen.has(value)?'checked':''}><span>${label}</span></label>`).join('');$('#sportCapability').innerHTML=config.ability.map(([value,label])=>`<label><input type="checkbox" name="readiness" value="${value}" ${chosen.has(value)?'checked':''}><span>${label}</span></label>`).join('');$('#qualificationSelect').innerHTML=config.awards.map(([value,label])=>`<option value="${value}" ${profile.qualification===value?'selected':''}>${label}</option>`).join('')}
async function locateHome(query){let response=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=gb,ie&q=${encodeURIComponent(query)}`,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error('Location lookup failed');let result=(await response.json())[0];if(!result)throw new Error('Area not found');return{label:result.display_name.split(',').slice(0,2).join(', '),lat:+result.lat,lon:+result.lon}}

function profileLabel(){return`${sports[state.freeSport]||'SUP'} · ${(state.skills[state.freeSport]||'beginner').replace(/^./,x=>x.toUpperCase())}`}
function inFreeArea(s){return !state.home||milesBetween(state.home,s)<=FREE_RADIUS_MILES}
function applyProfileMapFilter(){if(!map)return;Object.entries(spots).forEach(([id,s])=>{let visible=(s.hazardOnly||!s.sports||s.sports.includes(state.freeSport))&&inFreeArea(s),marker=markers[id];if(!marker)return;if(visible&&!map.hasLayer(marker))marker.addTo(map);else if(!visible&&map.hasLayer(marker))marker.removeFrom(map)});$$('#spotSelect option').forEach(option=>{if(!option.value)return;let s=spots[option.value],suitable=!s?.sports||s.sports.includes(state.freeSport);option.hidden=option.disabled=Boolean(s&&(!inFreeArea(s)||!suitable))})}
function updateProfileUI(){let button=$('#activeProfileButton');if(button){button.textContent=profileLabel();button.dataset.mode=state.freeSport==='sup'?'paddle':'wind'}$('#skillQuick').textContent=(state.skills[state.freeSport]||'beginner').replace(/^./,x=>x.toUpperCase());$('#profileInitials').textContent=(sports[state.freeSport]||'SUP').replace(/[^A-Za-z]/g,'').slice(0,2).toUpperCase();applyProfileMapFilter()}

openSetup=function(required=false){let sport=state.freeSport||'sup',sportInput=$(`#setupForm input[name="primary_sport"][value="${sport}"]`),level=state.skills[sport]||'beginner',levelInput=$(`#setupForm input[name="profile_skill"][value="${level}"]`),dialog=$('#setupDialog');if(sportInput)sportInput.checked=true;if(levelInput)levelInput.checked=true;$('#homeAreaInput').value=state.home?.query||'';renderReadiness(sport);dialog.classList.toggle('setup-required',required);dialog.dataset.required=required?'true':'false';if(!dialog.open)dialog.showModal()};
save=async function(){let form=$('#setupForm'),f=new FormData(form),sport=f.get('primary_sport')||'sup',skill=f.get('profile_skill')||'beginner',query=String(f.get('home_area')||'').trim(),dialog=$('#setupDialog');dialog.classList.add('setup-busy');$('#homeAreaError').hidden=true;try{let home=state.home?.query===query?state.home:await locateHome(query);home.query=query;state.home=home;state.freeSport=sport;state.sport=sport;state.mode=sport==='sup'?'paddle':'wind';state.skills[sport]=skill;state.skill=skill;state.profile={readiness:f.getAll('readiness'),qualification:f.get('qualification')||'none'};localStorage.setItem('shorewise-profile-v6',JSON.stringify({freeSport:sport,skills:state.skills,profile:state.profile,home:state.home,setupComplete:true}));hasSetup=true;dialog.dataset.required='false';dialog.classList.remove('setup-required');dialog.close();updateProfileUI();map?.setView([state.home.lat,state.home.lon],8);if(state.spot&&!inFreeArea(spots[state.spot])){state.spot='';state.live=null;$('#spotSelect').value=''}if(state.spot){render();updateMapSignals()}toast(`${profileLabel()} · local forecast around ${state.home.label}`)}catch(error){$('#homeAreaError').hidden=false}finally{dialog.classList.remove('setup-busy')}};
$('#profileButton').onclick=()=>openSetup(false);$('#skillQuick').onclick=()=>openSetup(false);$('#setupForm').onsubmit=event=>{event.preventDefault();save()};$$('#setupForm input[name="primary_sport"]').forEach(input=>input.onchange=()=>renderReadiness(input.value));$('#setupDialog').addEventListener('cancel',event=>{if($('#setupDialog').dataset.required==='true')event.preventDefault()});$('#upgradeButton').onclick=()=>toast('Premium preview: nationwide travel search, several sport profiles and charger planning — payments are not live yet.');

let fullMap=false;function setFullMap(on){fullMap=on;let stage=$('.map-stage'),button=$('#mapFullscreen');stage.classList.toggle('is-fullscreen',on);document.body.classList.toggle('map-open',on);button.textContent=on?'Close map':'Full screen';button.setAttribute('aria-label',on?'Close full-screen map':'Open full-screen map');setTimeout(()=>map?.invalidateSize(),120)}
$('#mapFullscreen').onclick=()=>setFullMap(!fullMap);document.addEventListener('keydown',event=>{if(event.key==='Escape'&&fullMap)setFullMap(false)});

updateProfileUI();
if(!hasSetup)setTimeout(()=>openSetup(true),120);


